### ISSUE TITLE
Feature Request: Allow drafts without bots 

### ISSUE THREAD

**Issue by Quiquex** [jjallaire/draftpod#70]
Hey there, I've been using and enjoying draftpod a lot lately due the pandemic, but sadly most of the time my group of drafters is not 8 people.
Would it be possible to add an option to not add bots to the table? I know it's not the same thing but it's kind of a bummer to draft with 6/7 real people joking and laughing via voice comms and 1/2 bots.

**Comment by jjallaire** [comment]
There isn't an option to do this right now. My feeling is that a table that opens 24 packs will have greater deck variety (including deeper variations of some archetypes). If you ditch the bots you'd have 18 or 21 packs which I think is a net negative.

**Comment by Quiquex** [comment]
Yeah totally agree, less than 8 players tables are not good training for nor simulation of a proper rl draft.
But the option could be useful for less serious and numerous groups (in desperate times...)

**Comment by Quiquex** [comment]
I'd like to take a shot at this, if that's ok.
I forked the repo but firebase is refusing my requests:
```
message: "Requests from referer http://localhost:8080/play/?format=draft are blocked."
status: "PERMISSION_DENIED"
```
Do I need to setup my own app + buckets for development?

**Comment by jjallaire** [comment]
Yes, I think you would indeed need to setup your own app + buckets (as the localhost key is naturally a private one).

My big concern about this feature is that it will be overly complex to implement (due to assumptions baked into the code about 8 players) and therefore make the system a bit more brittle (and harder to change in other ways). I also continue to believe that drafts are better with 24 packs so am not sure how widely it would be used.

**Comment by Quiquex** [comment]
After looking at the code today, I agree with you. Too many changes needed for what would be something that won't be used that much.
